/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Keth Dominic
 */
public class RecentIFrame extends javax.swing.JInternalFrame {
    DefaultTableModel model;
    Object tablerow [][];
    String tablecol []= {"Branch","Location","<html><left>Reservation<br>Date","Check-in","Check-out","<html><left>Room<br>Number","<html><left>Room<br>Type","<html><left>Days<br>Occupied","<html><left>Room<br>Price","<html><left>Price<br>Payed (Php)"};
    
    String id;
    /**
     * Creates new form recentIFrame
     */
    
    QueryProcessor dbprocess;
    
    public RecentIFrame() {
        initComponents();
        dbprocess = new QueryProcessor();

    }

    
    public void displayRecentTabble(String userId){
        id = userId;
        String searchQuery = "SELECT `branch`, `location`, `reservation_date`, `check_in`, `check_out`, `room_number`, `room_type`,`days_occupied`,`room_price`, `price_payed` FROM `recent_bookings_table` where `customer_id` = '"+id+"'";
        tablerow = dbprocess.getAllRecord(searchQuery);
        
        model = new DefaultTableModel(tablerow,tablecol);
        
        recentTable.setModel(model);
        recentTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        recentTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        recentTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        recentTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        recentTable.getColumnModel().getColumn(7).setPreferredWidth(75);

        
        if (tablerow == null){
            resultLabel.setText("No recent bookings found.");
        }
        else{
            resultLabel.setText("");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recentTable = new javax.swing.JTable();

        setTitle("Recent Bookings");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/bookingsystem/images/gblogo.png"))); // NOI18N
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(1060, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(153, 153, 153));
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 310, 30));

        recentTable.setForeground(new java.awt.Color(0, 0, 255));
        recentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        recentTable.setName(""); // NOI18N
        recentTable.setRowHeight(40);
        recentTable.setRowSelectionAllowed(false);
        recentTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(recentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recentTable;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
