/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Keth Dominic
 */
public class Settingspanel extends javax.swing.JFrame {
    
    String id;
    Boolean isAdmin = false;
    /**
     * Creates new form Settingspanel
     */
    QueryProcessor dbprocess;
    
    
    public Settingspanel() {
        initComponents();
        dbprocess = new QueryProcessor ();

    }
  
    public void displayAccInformation(String userId){

        id = userId;

        String firstName, lastName, userEmail, userAddress;
        firstName = dbprocess.getSpecificField("Select `user_fname` from `users_info` where `user_id` ='"+id+"' ");
        lastName = dbprocess.getSpecificField("Select `user_lname` from `users_info` where `user_id` ='"+id+"' ");
        userEmail = dbprocess.getSpecificField("Select `user_email` from `users_info` where `user_id` ='"+id+"' ");
        userAddress = dbprocess.getSpecificField("Select `user_address` from `users_info` where `user_id` ='"+id+"' ");
        fullNameLabel1.setText(firstName+" "+lastName);
        emailLabel.setText(userEmail);
        addressLabel1.setText(userAddress);
        
    }
    public void recentFrame(String userId){
        RecentIFrame recentFrame = new RecentIFrame();
        recentFrame.displayRecentTabble(userId);
        recentFrame.setVisible(true);
        settingsDPane.add(recentFrame);
    }
    
    public void adminLogin(){
        String message;
        message = "Enter Admin Passowrd";
        Object adminPass = null;
        try{
            do{
                adminPass = JOptionPane.showInputDialog(null, message, "GBHotel Admin",JOptionPane.QUESTION_MESSAGE, new ImageIcon("C:\\Users\\Keth Dominic\\Documents\\NetBeansProjects\\BookingSystem\\src\\bookingsystem\\images\\icons8_administrator_male_30px.png"),null, null);
                message = "Wrong Password";
                if(adminPass.equals("admin")){
                    AdminIFrame adminFrame = new AdminIFrame();
                    settingsDPane.removeAll();
                    adminFrame.setVisible(true);
                    settingsDPane.add(adminFrame);
                    isAdmin = true;
                }
            }while(!adminPass.equals("admin"));
        }
        catch (Exception e){    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settingsDPane = new javax.swing.JDesktopPane();
        adminBtn = new javax.swing.JButton();
        recentBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        fullNameLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Settings");
        setIconImage(new ImageIcon("C:\\Users\\Keth Dominic\\Documents\\NetBeansProjects\\BookingSystem\\src\\bookingsystem\\images\\gblogo.png").getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsDPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout settingsDPaneLayout = new javax.swing.GroupLayout(settingsDPane);
        settingsDPane.setLayout(settingsDPaneLayout);
        settingsDPaneLayout.setHorizontalGroup(
            settingsDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        settingsDPaneLayout.setVerticalGroup(
            settingsDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(settingsDPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1060, 440));

        adminBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adminBtn.setForeground(new java.awt.Color(0, 0, 110));
        adminBtn.setText("Admin Area");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 170, 40));

        recentBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        recentBtn.setForeground(new java.awt.Color(0, 0, 110));
        recentBtn.setText("Recent Bookings");
        recentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(recentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 40));

        editBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 110));
        editBtn.setText("Edit Profile");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, 40));

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 370, 30));

        fullNameLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(fullNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, 30));

        addressLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(addressLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 300, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 110));
        jLabel1.setText("Account Information");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Address:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("E-mail:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        settingsDPane.removeAll();
        EditProfileIFrame editFrame = new EditProfileIFrame();
        editFrame.setInfoToTextField(id);
        editFrame.setVisible(true);
        settingsDPane.add(editFrame);
    }//GEN-LAST:event_editBtnActionPerformed

    private void recentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recentBtnActionPerformed
        // TODO add your handling code here:
        settingsDPane.removeAll();
        recentFrame(id);
    }//GEN-LAST:event_recentBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        if(isAdmin == false){
            adminLogin();
        }
        else{
            AdminIFrame adminFrame = new AdminIFrame();
            settingsDPane.removeAll();
            adminFrame.setVisible(true);
            settingsDPane.add(adminFrame);
        }
    }//GEN-LAST:event_adminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settingspanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settingspanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settingspanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settingspanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settingspanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fullNameLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton recentBtn;
    private javax.swing.JDesktopPane settingsDPane;
    // End of variables declaration//GEN-END:variables
}
